package com.example.jinha.myapplication;

import android.content.Context;
import android.view.View;
import android.view.ViewGroup;
import android.widget.BaseAdapter;
import android.widget.GridView;
import android.widget.ImageView;

public class GridViewAdapter extends BaseAdapter {
    private Integer[] routeInt;
    private Context mContext;
    private int routeMax = 0;

    public GridViewAdapter(Context c, Integer[] routeInt)
    {
        mContext = c;
        this.routeInt = routeInt;
        for(int i=0; i<routeInt.length; i++) {
            if (routeMax < routeInt[i])
                routeMax = routeInt[i];
        }
    }

    public int getCount(){
        return mThumbIds.length;
    }
    public Object getItem(int position){
        return null;
    }
    public long getItemId(int position){
        return 0;
    }

    public View getView(int position, View convertView, ViewGroup parent){
        ImageView imageView;
        if(convertView == null){

            imageView = new ImageView(mContext);
            imageView.setLayoutParams(new GridView.LayoutParams(42, 50));
            //imageView.setScaleType(ImageView.ScaleType.CENTER_CROP);
            imageView.setPadding(2, 2, 2, 2);
        }
        else{
            imageView = (ImageView)convertView;
        }
        double opacity = ((double)routeInt[position] / (double)routeMax);
        imageView.setImageAlpha(30 + ((int)(opacity * 225)));
        imageView.setImageResource(mThumbIds[position]);

        return imageView;
    }

    private Integer[] mThumbIds = {
            R.drawable.cage_background_001, R.drawable.cage_background_002, R.drawable.cage_background_003,
            R.drawable.cage_background_004, R.drawable.cage_background_005, R.drawable.cage_background_006,
            R.drawable.cage_background_007, R.drawable.cage_background_008, R.drawable.cage_background_009,
            R.drawable.cage_background_010, R.drawable.cage_background_011, R.drawable.cage_background_012,
            R.drawable.cage_background_013, R.drawable.cage_background_014, R.drawable.cage_background_015,
            R.drawable.cage_background_016, R.drawable.cage_background_017, R.drawable.cage_background_018,
            R.drawable.cage_background_019, R.drawable.cage_background_020, R.drawable.cage_background_021,
            R.drawable.cage_background_022, R.drawable.cage_background_023, R.drawable.cage_background_024,
            R.drawable.cage_background_025, R.drawable.cage_background_026, R.drawable.cage_background_027,
            R.drawable.cage_background_028, R.drawable.cage_background_029, R.drawable.cage_background_030,
            R.drawable.cage_background_031, R.drawable.cage_background_032, R.drawable.cage_background_033,
            R.drawable.cage_background_034, R.drawable.cage_background_035, R.drawable.cage_background_036,
            R.drawable.cage_background_037, R.drawable.cage_background_038, R.drawable.cage_background_039,
            R.drawable.cage_background_040, R.drawable.cage_background_041, R.drawable.cage_background_042,
            R.drawable.cage_background_043, R.drawable.cage_background_044, R.drawable.cage_background_045,
            R.drawable.cage_background_046, R.drawable.cage_background_047, R.drawable.cage_background_048,
            R.drawable.cage_background_049, R.drawable.cage_background_050, R.drawable.cage_background_051,
            R.drawable.cage_background_052, R.drawable.cage_background_053, R.drawable.cage_background_054,
            R.drawable.cage_background_055, R.drawable.cage_background_056, R.drawable.cage_background_057,
            R.drawable.cage_background_058, R.drawable.cage_background_059, R.drawable.cage_background_060,
            R.drawable.cage_background_061, R.drawable.cage_background_062, R.drawable.cage_background_063,
            R.drawable.cage_background_064, R.drawable.cage_background_065, R.drawable.cage_background_066,
            R.drawable.cage_background_067, R.drawable.cage_background_068, R.drawable.cage_background_069,
            R.drawable.cage_background_070, R.drawable.cage_background_071, R.drawable.cage_background_072,
            R.drawable.cage_background_073, R.drawable.cage_background_074, R.drawable.cage_background_075,
            R.drawable.cage_background_076, R.drawable.cage_background_077, R.drawable.cage_background_078,
            R.drawable.cage_background_079, R.drawable.cage_background_080, R.drawable.cage_background_081,
            R.drawable.cage_background_082, R.drawable.cage_background_083, R.drawable.cage_background_084,
            R.drawable.cage_background_085, R.drawable.cage_background_086, R.drawable.cage_background_087,
            R.drawable.cage_background_088, R.drawable.cage_background_089, R.drawable.cage_background_090,
            R.drawable.cage_background_091, R.drawable.cage_background_092, R.drawable.cage_background_093,
            R.drawable.cage_background_094, R.drawable.cage_background_095, R.drawable.cage_background_096,
            R.drawable.cage_background_097, R.drawable.cage_background_098, R.drawable.cage_background_099,
            R.drawable.cage_background_100,
            R.drawable.cage_background_101, R.drawable.cage_background_102, R.drawable.cage_background_103,
            R.drawable.cage_background_104, R.drawable.cage_background_105, R.drawable.cage_background_106,
            R.drawable.cage_background_107, R.drawable.cage_background_108, R.drawable.cage_background_109,
            R.drawable.cage_background_110, R.drawable.cage_background_111, R.drawable.cage_background_112,
            R.drawable.cage_background_113, R.drawable.cage_background_114, R.drawable.cage_background_115,
            R.drawable.cage_background_116, R.drawable.cage_background_117, R.drawable.cage_background_118,
            R.drawable.cage_background_119, R.drawable.cage_background_120, R.drawable.cage_background_121,
            R.drawable.cage_background_122, R.drawable.cage_background_123, R.drawable.cage_background_124,
            R.drawable.cage_background_125, R.drawable.cage_background_126, R.drawable.cage_background_127,
            R.drawable.cage_background_128, R.drawable.cage_background_129, R.drawable.cage_background_130,
            R.drawable.cage_background_131, R.drawable.cage_background_132, R.drawable.cage_background_133,
            R.drawable.cage_background_134, R.drawable.cage_background_135, R.drawable.cage_background_136,
            R.drawable.cage_background_137, R.drawable.cage_background_138, R.drawable.cage_background_139,
            R.drawable.cage_background_140, R.drawable.cage_background_141, R.drawable.cage_background_142,
            R.drawable.cage_background_143, R.drawable.cage_background_144, R.drawable.cage_background_145,
            R.drawable.cage_background_146, R.drawable.cage_background_147, R.drawable.cage_background_148,
            R.drawable.cage_background_149, R.drawable.cage_background_150, R.drawable.cage_background_151,
            R.drawable.cage_background_152, R.drawable.cage_background_153, R.drawable.cage_background_154,
            R.drawable.cage_background_155, R.drawable.cage_background_156, R.drawable.cage_background_157,
            R.drawable.cage_background_158, R.drawable.cage_background_159, R.drawable.cage_background_160,
            R.drawable.cage_background_161, R.drawable.cage_background_162, R.drawable.cage_background_163,
            R.drawable.cage_background_164, R.drawable.cage_background_165, R.drawable.cage_background_166,
            R.drawable.cage_background_167, R.drawable.cage_background_168, R.drawable.cage_background_169,
            R.drawable.cage_background_170, R.drawable.cage_background_171, R.drawable.cage_background_172,
            R.drawable.cage_background_173, R.drawable.cage_background_174, R.drawable.cage_background_175,
            R.drawable.cage_background_176, R.drawable.cage_background_177, R.drawable.cage_background_178,
            R.drawable.cage_background_179, R.drawable.cage_background_180, R.drawable.cage_background_181,
            R.drawable.cage_background_182, R.drawable.cage_background_183, R.drawable.cage_background_184,
            R.drawable.cage_background_185, R.drawable.cage_background_186, R.drawable.cage_background_187,
            R.drawable.cage_background_188, R.drawable.cage_background_189, R.drawable.cage_background_190,
            R.drawable.cage_background_191, R.drawable.cage_background_192, R.drawable.cage_background_193,
            R.drawable.cage_background_194, R.drawable.cage_background_195, R.drawable.cage_background_196,
            R.drawable.cage_background_197, R.drawable.cage_background_198, R.drawable.cage_background_199,
            R.drawable.cage_background_200, R.drawable.cage_background_201, R.drawable.cage_background_202,
            R.drawable.cage_background_203, R.drawable.cage_background_204, R.drawable.cage_background_205,
            R.drawable.cage_background_206, R.drawable.cage_background_207, R.drawable.cage_background_208,
            R.drawable.cage_background_209, R.drawable.cage_background_210, R.drawable.cage_background_211,
            R.drawable.cage_background_212, R.drawable.cage_background_213, R.drawable.cage_background_214,
            R.drawable.cage_background_215, R.drawable.cage_background_216, R.drawable.cage_background_217,
            R.drawable.cage_background_218, R.drawable.cage_background_219, R.drawable.cage_background_220,
            R.drawable.cage_background_221, R.drawable.cage_background_222, R.drawable.cage_background_223,
            R.drawable.cage_background_224, R.drawable.cage_background_225, R.drawable.cage_background_226,
            R.drawable.cage_background_227, R.drawable.cage_background_228, R.drawable.cage_background_229,
            R.drawable.cage_background_230, R.drawable.cage_background_231, R.drawable.cage_background_232,
            R.drawable.cage_background_233, R.drawable.cage_background_234, R.drawable.cage_background_235,
            R.drawable.cage_background_236, R.drawable.cage_background_237, R.drawable.cage_background_238,
            R.drawable.cage_background_239, R.drawable.cage_background_240, R.drawable.cage_background_241,
            R.drawable.cage_background_242, R.drawable.cage_background_243, R.drawable.cage_background_244,
            R.drawable.cage_background_245, R.drawable.cage_background_246, R.drawable.cage_background_247,
            R.drawable.cage_background_248, R.drawable.cage_background_249, R.drawable.cage_background_250,
            R.drawable.cage_background_251, R.drawable.cage_background_252, R.drawable.cage_background_253,
            R.drawable.cage_background_254, R.drawable.cage_background_255, R.drawable.cage_background_256,
            R.drawable.cage_background_257, R.drawable.cage_background_258, R.drawable.cage_background_259,
            R.drawable.cage_background_260, R.drawable.cage_background_261, R.drawable.cage_background_262,
            R.drawable.cage_background_263, R.drawable.cage_background_264, R.drawable.cage_background_265,
            R.drawable.cage_background_266, R.drawable.cage_background_267, R.drawable.cage_background_268,
            R.drawable.cage_background_269, R.drawable.cage_background_270, R.drawable.cage_background_271,
            R.drawable.cage_background_272, R.drawable.cage_background_273, R.drawable.cage_background_274,
            R.drawable.cage_background_275, R.drawable.cage_background_276, R.drawable.cage_background_277,
            R.drawable.cage_background_278, R.drawable.cage_background_279, R.drawable.cage_background_280,
            R.drawable.cage_background_281, R.drawable.cage_background_282, R.drawable.cage_background_283,
            R.drawable.cage_background_284, R.drawable.cage_background_285, R.drawable.cage_background_286,
            R.drawable.cage_background_287, R.drawable.cage_background_288, R.drawable.cage_background_289,
            R.drawable.cage_background_290, R.drawable.cage_background_291, R.drawable.cage_background_292,
            R.drawable.cage_background_293, R.drawable.cage_background_294, R.drawable.cage_background_295,
            R.drawable.cage_background_296, R.drawable.cage_background_297, R.drawable.cage_background_298,
            R.drawable.cage_background_299, R.drawable.cage_background_300, R.drawable.cage_background_301,
            R.drawable.cage_background_302, R.drawable.cage_background_303, R.drawable.cage_background_304,
            R.drawable.cage_background_305, R.drawable.cage_background_306, R.drawable.cage_background_307,
            R.drawable.cage_background_308, R.drawable.cage_background_309, R.drawable.cage_background_310,
            R.drawable.cage_background_311, R.drawable.cage_background_312, R.drawable.cage_background_313,
            R.drawable.cage_background_314, R.drawable.cage_background_315, R.drawable.cage_background_316,
            R.drawable.cage_background_317, R.drawable.cage_background_318, R.drawable.cage_background_319,
            R.drawable.cage_background_320, R.drawable.cage_background_321, R.drawable.cage_background_322,
            R.drawable.cage_background_323, R.drawable.cage_background_324, R.drawable.cage_background_325,
            R.drawable.cage_background_326, R.drawable.cage_background_327, R.drawable.cage_background_328,
            R.drawable.cage_background_329, R.drawable.cage_background_330, R.drawable.cage_background_331,
            R.drawable.cage_background_332, R.drawable.cage_background_333, R.drawable.cage_background_334,
            R.drawable.cage_background_335, R.drawable.cage_background_336, R.drawable.cage_background_337,
            R.drawable.cage_background_338, R.drawable.cage_background_339, R.drawable.cage_background_340,
            R.drawable.cage_background_341, R.drawable.cage_background_342, R.drawable.cage_background_343,
            R.drawable.cage_background_344, R.drawable.cage_background_345, R.drawable.cage_background_346,
            R.drawable.cage_background_347, R.drawable.cage_background_348, R.drawable.cage_background_349,
            R.drawable.cage_background_350, R.drawable.cage_background_351, R.drawable.cage_background_352,
            R.drawable.cage_background_353, R.drawable.cage_background_354, R.drawable.cage_background_355,
            R.drawable.cage_background_356, R.drawable.cage_background_357, R.drawable.cage_background_358,
            R.drawable.cage_background_359, R.drawable.cage_background_360, R.drawable.cage_background_361,
            R.drawable.cage_background_362, R.drawable.cage_background_363, R.drawable.cage_background_364,
            R.drawable.cage_background_365, R.drawable.cage_background_366, R.drawable.cage_background_367,
            R.drawable.cage_background_368, R.drawable.cage_background_369, R.drawable.cage_background_370,
            R.drawable.cage_background_371, R.drawable.cage_background_372, R.drawable.cage_background_373,
            R.drawable.cage_background_374, R.drawable.cage_background_375, R.drawable.cage_background_376,
            R.drawable.cage_background_377, R.drawable.cage_background_378, R.drawable.cage_background_379,
            R.drawable.cage_background_380, R.drawable.cage_background_381, R.drawable.cage_background_382,
            R.drawable.cage_background_383, R.drawable.cage_background_384, R.drawable.cage_background_385,
            R.drawable.cage_background_386, R.drawable.cage_background_387, R.drawable.cage_background_388,
            R.drawable.cage_background_389, R.drawable.cage_background_390, R.drawable.cage_background_391,
            R.drawable.cage_background_392, R.drawable.cage_background_393, R.drawable.cage_background_394,
            R.drawable.cage_background_395, R.drawable.cage_background_396, R.drawable.cage_background_397,
            R.drawable.cage_background_398, R.drawable.cage_background_399, R.drawable.cage_background_400,
            R.drawable.cage_background_401, R.drawable.cage_background_402, R.drawable.cage_background_403,
            R.drawable.cage_background_404, R.drawable.cage_background_405, R.drawable.cage_background_406,
            R.drawable.cage_background_407, R.drawable.cage_background_408, R.drawable.cage_background_409,
            R.drawable.cage_background_410, R.drawable.cage_background_411, R.drawable.cage_background_412,
            R.drawable.cage_background_413, R.drawable.cage_background_414, R.drawable.cage_background_415,
            R.drawable.cage_background_416, R.drawable.cage_background_417, R.drawable.cage_background_418,
            R.drawable.cage_background_419, R.drawable.cage_background_420, R.drawable.cage_background_421,
            R.drawable.cage_background_422, R.drawable.cage_background_423, R.drawable.cage_background_424,
            R.drawable.cage_background_425, R.drawable.cage_background_426, R.drawable.cage_background_427,
            R.drawable.cage_background_428, R.drawable.cage_background_429, R.drawable.cage_background_430,
            R.drawable.cage_background_431, R.drawable.cage_background_432, R.drawable.cage_background_433,
            R.drawable.cage_background_434, R.drawable.cage_background_435, R.drawable.cage_background_436,
            R.drawable.cage_background_437, R.drawable.cage_background_438, R.drawable.cage_background_439,
            R.drawable.cage_background_440, R.drawable.cage_background_441, R.drawable.cage_background_442,
            R.drawable.cage_background_443, R.drawable.cage_background_444, R.drawable.cage_background_445,
            R.drawable.cage_background_446, R.drawable.cage_background_447, R.drawable.cage_background_448,
            R.drawable.cage_background_449, R.drawable.cage_background_450, R.drawable.cage_background_451,
            R.drawable.cage_background_452, R.drawable.cage_background_453, R.drawable.cage_background_454,
            R.drawable.cage_background_455, R.drawable.cage_background_456, R.drawable.cage_background_457,
            R.drawable.cage_background_458, R.drawable.cage_background_459, R.drawable.cage_background_460,
            R.drawable.cage_background_461, R.drawable.cage_background_462, R.drawable.cage_background_463,
            R.drawable.cage_background_464, R.drawable.cage_background_465, R.drawable.cage_background_466,
            R.drawable.cage_background_467, R.drawable.cage_background_468, R.drawable.cage_background_469,
            R.drawable.cage_background_470, R.drawable.cage_background_471, R.drawable.cage_background_472,
            R.drawable.cage_background_473, R.drawable.cage_background_474, R.drawable.cage_background_475,
            R.drawable.cage_background_476, R.drawable.cage_background_477, R.drawable.cage_background_478,
            R.drawable.cage_background_479, R.drawable.cage_background_480, R.drawable.cage_background_481,
            R.drawable.cage_background_482, R.drawable.cage_background_483, R.drawable.cage_background_484,
            R.drawable.cage_background_485, R.drawable.cage_background_486, R.drawable.cage_background_487,
            R.drawable.cage_background_488, R.drawable.cage_background_489, R.drawable.cage_background_490,
            R.drawable.cage_background_491, R.drawable.cage_background_492, R.drawable.cage_background_493,
            R.drawable.cage_background_494, R.drawable.cage_background_495, R.drawable.cage_background_496,
            R.drawable.cage_background_497, R.drawable.cage_background_498, R.drawable.cage_background_499,
            R.drawable.cage_background_500, R.drawable.cage_background_501, R.drawable.cage_background_502,
            R.drawable.cage_background_503, R.drawable.cage_background_504, R.drawable.cage_background_505,
            R.drawable.cage_background_506, R.drawable.cage_background_507, R.drawable.cage_background_508,
            R.drawable.cage_background_509, R.drawable.cage_background_510, R.drawable.cage_background_511,
            R.drawable.cage_background_512, R.drawable.cage_background_513, R.drawable.cage_background_514,
            R.drawable.cage_background_515, R.drawable.cage_background_516, R.drawable.cage_background_517,
            R.drawable.cage_background_518, R.drawable.cage_background_519, R.drawable.cage_background_520,
            R.drawable.cage_background_521, R.drawable.cage_background_522, R.drawable.cage_background_523,
            R.drawable.cage_background_524, R.drawable.cage_background_525, R.drawable.cage_background_526,
            R.drawable.cage_background_527, R.drawable.cage_background_528, R.drawable.cage_background_529,
            R.drawable.cage_background_530, R.drawable.cage_background_531, R.drawable.cage_background_532,
            R.drawable.cage_background_533, R.drawable.cage_background_534, R.drawable.cage_background_535,
            R.drawable.cage_background_536, R.drawable.cage_background_537, R.drawable.cage_background_538,
            R.drawable.cage_background_539, R.drawable.cage_background_540, R.drawable.cage_background_541,
            R.drawable.cage_background_542, R.drawable.cage_background_543, R.drawable.cage_background_544,
            R.drawable.cage_background_545, R.drawable.cage_background_546, R.drawable.cage_background_547,
            R.drawable.cage_background_548, R.drawable.cage_background_549, R.drawable.cage_background_550,
            R.drawable.cage_background_551, R.drawable.cage_background_552, R.drawable.cage_background_553,
            R.drawable.cage_background_554, R.drawable.cage_background_555, R.drawable.cage_background_556,
            R.drawable.cage_background_557, R.drawable.cage_background_558, R.drawable.cage_background_559,
            R.drawable.cage_background_560, R.drawable.cage_background_561, R.drawable.cage_background_562,
            R.drawable.cage_background_563, R.drawable.cage_background_564, R.drawable.cage_background_565,
            R.drawable.cage_background_566, R.drawable.cage_background_567, R.drawable.cage_background_568,
            R.drawable.cage_background_569, R.drawable.cage_background_570, R.drawable.cage_background_571,
            R.drawable.cage_background_572, R.drawable.cage_background_573, R.drawable.cage_background_574,
            R.drawable.cage_background_575, R.drawable.cage_background_576, R.drawable.cage_background_577,
            R.drawable.cage_background_578, R.drawable.cage_background_579, R.drawable.cage_background_580,
            R.drawable.cage_background_581, R.drawable.cage_background_582, R.drawable.cage_background_583,
            R.drawable.cage_background_584, R.drawable.cage_background_585, R.drawable.cage_background_586,
            R.drawable.cage_background_587, R.drawable.cage_background_588, R.drawable.cage_background_589,
            R.drawable.cage_background_590, R.drawable.cage_background_591, R.drawable.cage_background_592,
            R.drawable.cage_background_593, R.drawable.cage_background_594, R.drawable.cage_background_595,
            R.drawable.cage_background_596, R.drawable.cage_background_597, R.drawable.cage_background_598,
            R.drawable.cage_background_599, R.drawable.cage_background_600, R.drawable.cage_background_601,
            R.drawable.cage_background_602, R.drawable.cage_background_603, R.drawable.cage_background_604,
            R.drawable.cage_background_605, R.drawable.cage_background_606, R.drawable.cage_background_607,
            R.drawable.cage_background_608, R.drawable.cage_background_609, R.drawable.cage_background_610,
            R.drawable.cage_background_611, R.drawable.cage_background_612, R.drawable.cage_background_613,
            R.drawable.cage_background_614, R.drawable.cage_background_615, R.drawable.cage_background_616,
            R.drawable.cage_background_617, R.drawable.cage_background_618, R.drawable.cage_background_619,
            R.drawable.cage_background_620, R.drawable.cage_background_621, R.drawable.cage_background_622,
            R.drawable.cage_background_623, R.drawable.cage_background_624, R.drawable.cage_background_625,
            R.drawable.cage_background_626, R.drawable.cage_background_627, R.drawable.cage_background_628,
            R.drawable.cage_background_629, R.drawable.cage_background_630, R.drawable.cage_background_631,
            R.drawable.cage_background_632, R.drawable.cage_background_633, R.drawable.cage_background_634,
            R.drawable.cage_background_635, R.drawable.cage_background_636, R.drawable.cage_background_637,
            R.drawable.cage_background_638, R.drawable.cage_background_639, R.drawable.cage_background_640,
            R.drawable.cage_background_641, R.drawable.cage_background_642, R.drawable.cage_background_643,
            R.drawable.cage_background_644, R.drawable.cage_background_645, R.drawable.cage_background_646,
            R.drawable.cage_background_647, R.drawable.cage_background_648, R.drawable.cage_background_649,
            R.drawable.cage_background_650, R.drawable.cage_background_651, R.drawable.cage_background_652,
            R.drawable.cage_background_653, R.drawable.cage_background_654, R.drawable.cage_background_655,
            R.drawable.cage_background_656, R.drawable.cage_background_657, R.drawable.cage_background_658,
            R.drawable.cage_background_659, R.drawable.cage_background_660, R.drawable.cage_background_661,
            R.drawable.cage_background_662, R.drawable.cage_background_663, R.drawable.cage_background_664,
            R.drawable.cage_background_665, R.drawable.cage_background_666, R.drawable.cage_background_667,
            R.drawable.cage_background_668, R.drawable.cage_background_669, R.drawable.cage_background_670,
            R.drawable.cage_background_671, R.drawable.cage_background_672, R.drawable.cage_background_673,
            R.drawable.cage_background_674, R.drawable.cage_background_675, R.drawable.cage_background_676,
            R.drawable.cage_background_677, R.drawable.cage_background_678, R.drawable.cage_background_679,
            R.drawable.cage_background_680, R.drawable.cage_background_681, R.drawable.cage_background_682,
            R.drawable.cage_background_683, R.drawable.cage_background_684, R.drawable.cage_background_685,
            R.drawable.cage_background_686, R.drawable.cage_background_687, R.drawable.cage_background_688,
            R.drawable.cage_background_689, R.drawable.cage_background_690, R.drawable.cage_background_691,
            R.drawable.cage_background_692, R.drawable.cage_background_693, R.drawable.cage_background_694,
            R.drawable.cage_background_695, R.drawable.cage_background_696, R.drawable.cage_background_697,
            R.drawable.cage_background_698, R.drawable.cage_background_699, R.drawable.cage_background_700,
            R.drawable.cage_background_701, R.drawable.cage_background_702, R.drawable.cage_background_703,
            R.drawable.cage_background_704, R.drawable.cage_background_705, R.drawable.cage_background_706,
            R.drawable.cage_background_707, R.drawable.cage_background_708, R.drawable.cage_background_709,
            R.drawable.cage_background_710, R.drawable.cage_background_711, R.drawable.cage_background_712,
            R.drawable.cage_background_713, R.drawable.cage_background_714, R.drawable.cage_background_715,
            R.drawable.cage_background_716, R.drawable.cage_background_717, R.drawable.cage_background_718,
            R.drawable.cage_background_719, R.drawable.cage_background_720, R.drawable.cage_background_721,
            R.drawable.cage_background_722, R.drawable.cage_background_723, R.drawable.cage_background_724,
            R.drawable.cage_background_725, R.drawable.cage_background_726, R.drawable.cage_background_727,
            R.drawable.cage_background_728, R.drawable.cage_background_729, R.drawable.cage_background_730,
            R.drawable.cage_background_731, R.drawable.cage_background_732, R.drawable.cage_background_733,
            R.drawable.cage_background_734, R.drawable.cage_background_735, R.drawable.cage_background_736,
            R.drawable.cage_background_737, R.drawable.cage_background_738, R.drawable.cage_background_739,
            R.drawable.cage_background_740, R.drawable.cage_background_741, R.drawable.cage_background_742,
            R.drawable.cage_background_743, R.drawable.cage_background_744, R.drawable.cage_background_745,
            R.drawable.cage_background_746, R.drawable.cage_background_747, R.drawable.cage_background_748,
            R.drawable.cage_background_749, R.drawable.cage_background_750, R.drawable.cage_background_751,
            R.drawable.cage_background_752, R.drawable.cage_background_753, R.drawable.cage_background_754,
            R.drawable.cage_background_755, R.drawable.cage_background_756, R.drawable.cage_background_757,
            R.drawable.cage_background_758, R.drawable.cage_background_759, R.drawable.cage_background_760,
            R.drawable.cage_background_761, R.drawable.cage_background_762, R.drawable.cage_background_763,
            R.drawable.cage_background_764, R.drawable.cage_background_765, R.drawable.cage_background_766,
            R.drawable.cage_background_767, R.drawable.cage_background_768,
    };
}
